import React from 'react';
import { X, FileText, Download, Eye, Calendar, Award } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { useUser } from '../contexts/UserContext';

interface LabReportsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function LabReportsModal({ isOpen, onClose }: LabReportsModalProps) {
  const { userData } = useUser();
  const reports = userData.labReports;

  const downloadReport = (report: any) => {
    const content = `
BRIDGE 86-51 LAB REPORT
========================

Report ID: ${report.id}
Experiment: ${report.experimentTitle} (${report.experimentId})
Generated: ${new Date(report.generatedAt).toLocaleString()}
Score: ${report.score}%

ANALYSIS RESULTS
----------------
Cycle Efficiency: ${report.analysisResults.cycleEfficiency}%
Power Consumption: ${report.analysisResults.powerConsumption}
Bus Status: ${report.analysisResults.busStatus}

VIVA QUESTIONS & ANSWERS
-------------------------
${report.vivaAnswers.map((qa: any, i: number) => `
Q${i + 1}: ${qa.question}
A${i + 1}: ${qa.answer || 'Not answered'}
`).join('\n')}

Generated by Bridge 86-51 Microarchitecture Lab
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.experimentId}_Report_${report.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/50 backdrop-blur-sm z-[100]"
          />

          {/* Modal */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            className="fixed inset-0 z-[101] flex items-center justify-center p-4"
          >
            <div className="bg-white dark:bg-slate-800 rounded-3xl shadow-2xl max-w-5xl w-full max-h-[90vh] overflow-hidden">
              {/* Header */}
              <div className="bg-gradient-to-r from-emerald-600 to-teal-500 dark:from-emerald-700 dark:to-teal-600 p-6 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm">
                    <FileText size={24} className="text-white" />
                  </div>
                  <div>
                    <h2 className="text-white font-bold text-xl">Lab Reports</h2>
                    <p className="text-white/80 text-sm">{reports.length} reports generated</p>
                  </div>
                </div>
                <button
                  onClick={onClose}
                  className="w-10 h-10 rounded-xl bg-white/10 hover:bg-white/20 flex items-center justify-center transition-colors"
                >
                  <X size={20} className="text-white" />
                </button>
              </div>

              {/* Content */}
              <div className="p-8 overflow-y-auto max-h-[calc(90vh-140px)]">
                {reports.length === 0 ? (
                  <div className="text-center py-16">
                    <div className="w-24 h-24 bg-slate-100 dark:bg-slate-700 rounded-full flex items-center justify-center mx-auto mb-6">
                      <FileText size={48} className="text-slate-300 dark:text-slate-500" />
                    </div>
                    <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-2">No Reports Yet</h3>
                    <p className="text-slate-500 dark:text-slate-400">
                      Complete and validate experiments to generate lab reports
                    </p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    {reports.map((report) => (
                      <motion.div
                        key={report.id}
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="p-6 bg-gradient-to-br from-slate-50 to-slate-100/50 dark:from-slate-700 dark:to-slate-800/50 rounded-2xl border border-slate-200 dark:border-slate-600 hover:shadow-lg transition-all"
                      >
                        <div className="flex items-start justify-between mb-4">
                          {/* Report Info */}
                          <div className="flex-1">
                            <div className="flex items-center gap-3 mb-2">
                              <div className="px-3 py-1 bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400 rounded-lg text-xs font-bold">
                                {report.experimentId}
                              </div>
                              <h3 className="font-bold text-slate-900 dark:text-white">{report.experimentTitle}</h3>
                            </div>
                            <div className="flex items-center gap-4 text-sm text-slate-500 dark:text-slate-400">
                              <div className="flex items-center gap-1">
                                <Calendar size={14} />
                                {new Date(report.generatedAt).toLocaleDateString()}
                              </div>
                              <div className="flex items-center gap-1">
                                <Award size={14} />
                                Score: {report.score}%
                              </div>
                            </div>
                          </div>

                          {/* Actions */}
                          <div className="flex items-center gap-2">
                            <button
                              onClick={() => downloadReport(report)}
                              className="p-3 bg-white dark:bg-slate-600 border border-slate-200 dark:border-slate-500 rounded-xl text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-500 hover:text-blue-600 dark:hover:text-blue-400 transition-all"
                              title="Download Report"
                            >
                              <Download size={18} />
                            </button>
                          </div>
                        </div>

                        {/* Analysis Results */}
                        <div className="grid grid-cols-3 gap-3 mb-4">
                          <div className="p-4 bg-white dark:bg-slate-600 rounded-xl border border-slate-100 dark:border-slate-500">
                            <div className="text-xs text-slate-500 dark:text-slate-400 mb-1">Cycle Efficiency</div>
                            <div className="text-lg font-bold text-slate-900 dark:text-white">
                              {report.analysisResults.cycleEfficiency}%
                            </div>
                          </div>
                          <div className="p-4 bg-white dark:bg-slate-600 rounded-xl border border-slate-100 dark:border-slate-500">
                            <div className="text-xs text-slate-500 dark:text-slate-400 mb-1">Power</div>
                            <div className="text-lg font-bold text-slate-900 dark:text-white">
                              {report.analysisResults.powerConsumption}
                            </div>
                          </div>
                          <div className="p-4 bg-white dark:bg-slate-600 rounded-xl border border-slate-100 dark:border-slate-500">
                            <div className="text-xs text-slate-500 dark:text-slate-400 mb-1">Bus Status</div>
                            <div className="text-lg font-bold text-slate-900 dark:text-white">
                              {report.analysisResults.busStatus}
                            </div>
                          </div>
                        </div>

                        {/* Viva Answers Summary */}
                        <div className="pt-4 border-t border-slate-200 dark:border-slate-600">
                          <div className="text-xs text-slate-500 dark:text-slate-400 mb-2">Viva Questions Answered</div>
                          <div className="flex items-center gap-2">
                            {report.vivaAnswers.map((qa: any, i: number) => (
                              <div
                                key={i}
                                className={`w-8 h-8 rounded-lg flex items-center justify-center text-xs font-bold ${
                                  qa.answer
                                    ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400'
                                    : 'bg-slate-200 dark:bg-slate-600 text-slate-500 dark:text-slate-400'
                                }`}
                              >
                                {i + 1}
                              </div>
                            ))}
                          </div>
                        </div>
                      </motion.div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}