import React from 'react';
import { useUser } from '../contexts/UserContext';
import { 
  FileText, 
  Download, 
  Calendar, 
  Award, 
  TrendingUp, 
  CheckCircle2,
  Clock,
  Zap,
  Search,
  Filter
} from 'lucide-react';
import { motion } from 'motion/react';

export function LabReportsPage() {
  const { userData } = useUser();
  const { labReports } = userData;
  const [searchQuery, setSearchQuery] = React.useState('');
  const [sortBy, setSortBy] = React.useState<'date' | 'score'>('date');

  const sortedReports = [...labReports].sort((a, b) => {
    if (sortBy === 'date') {
      return new Date(b.generatedAt).getTime() - new Date(a.generatedAt).getTime();
    }
    return b.score - a.score;
  });

  const filteredReports = sortedReports.filter(report =>
    report.experimentTitle.toLowerCase().includes(searchQuery.toLowerCase()) ||
    report.experimentId.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const averageScore = labReports.length > 0
    ? Math.round(labReports.reduce((sum, r) => sum + r.score, 0) / labReports.length)
    : 0;

  const handleDownload = (report: typeof labReports[0]) => {
    const content = `
LAB REPORT - ${report.experimentTitle}
Generated: ${new Date(report.generatedAt).toLocaleString()}
Score: ${report.score}%

VIVA QUESTIONS & ANSWERS:
${report.vivaAnswers.map((qa, i) => `
${i + 1}. ${qa.question}
   Answer: ${qa.answer}
`).join('\n')}

ANALYSIS RESULTS:
- Cycle Efficiency: ${report.analysisResults.cycleEfficiency}%
- Power Consumption: ${report.analysisResults.powerConsumption}
- Bus Status: ${report.analysisResults.busStatus}

---
Generated by Bridge 86-51 Microarchitecture Lab
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.experimentId}_Report_${report.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-8">
        <div className="flex items-center gap-4">
          <div className="w-14 h-14 bg-gradient-to-br from-emerald-500 to-teal-600 rounded-2xl flex items-center justify-center text-white shadow-xl shadow-emerald-200 dark:shadow-emerald-900/30">
            <FileText size={28} />
          </div>
          <div>
            <h1 className="text-3xl font-black text-slate-900 dark:text-white tracking-tight">Lab Reports</h1>
            <p className="text-slate-500 dark:text-slate-400 font-medium">All your generated experiment reports</p>
          </div>
        </div>

        <div className="text-right">
          <p className="text-3xl font-black text-emerald-600 dark:text-emerald-400">{labReports.length}</p>
          <p className="text-sm text-slate-500 dark:text-slate-400 font-medium">Total Reports</p>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-gradient-to-br from-blue-50 to-blue-100 dark:from-blue-900/20 dark:to-blue-800/20 rounded-2xl p-5 border border-blue-200 dark:border-blue-800"
        >
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-blue-700 dark:text-blue-300 font-bold mb-1">Average Score</p>
              <p className="text-3xl font-black text-blue-900 dark:text-blue-100">{averageScore}%</p>
            </div>
            <Award className="text-blue-500 dark:text-blue-400" size={32} />
          </div>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="bg-gradient-to-br from-purple-50 to-purple-100 dark:from-purple-900/20 dark:to-purple-800/20 rounded-2xl p-5 border border-purple-200 dark:border-purple-800"
        >
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-purple-700 dark:text-purple-300 font-bold mb-1">Perfect Scores</p>
              <p className="text-3xl font-black text-purple-900 dark:text-purple-100">
                {labReports.filter(r => r.score === 100).length}
              </p>
            </div>
            <CheckCircle2 className="text-purple-500 dark:text-purple-400" size={32} />
          </div>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="bg-gradient-to-br from-emerald-50 to-emerald-100 dark:from-emerald-900/20 dark:to-emerald-800/20 rounded-2xl p-5 border border-emerald-200 dark:border-emerald-800"
        >
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-emerald-700 dark:text-emerald-300 font-bold mb-1">This Month</p>
              <p className="text-3xl font-black text-emerald-900 dark:text-emerald-100">
                {labReports.filter(r => {
                  const reportDate = new Date(r.generatedAt);
                  const now = new Date();
                  return reportDate.getMonth() === now.getMonth() && 
                         reportDate.getFullYear() === now.getFullYear();
                }).length}
              </p>
            </div>
            <TrendingUp className="text-emerald-500 dark:text-emerald-400" size={32} />
          </div>
        </motion.div>
      </div>

      {/* Search and Filter */}
      <div className="flex gap-4 items-center">
        <div className="flex-1 relative">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={20} />
          <input
            type="text"
            placeholder="Search reports by experiment name or ID..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-12 pr-4 py-3 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl font-medium text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
          />
        </div>

        <div className="flex gap-2 items-center bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl p-1">
          <Filter size={18} className="text-slate-400 ml-2" />
          <button
            onClick={() => setSortBy('date')}
            className={`px-4 py-2 rounded-xl font-bold transition-all text-sm ${
              sortBy === 'date'
                ? 'bg-slate-900 dark:bg-white text-white dark:text-slate-900 shadow-md'
                : 'text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700'
            }`}
          >
            Date
          </button>
          <button
            onClick={() => setSortBy('score')}
            className={`px-4 py-2 rounded-xl font-bold transition-all text-sm ${
              sortBy === 'score'
                ? 'bg-slate-900 dark:bg-white text-white dark:text-slate-900 shadow-md'
                : 'text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700'
            }`}
          >
            Score
          </button>
        </div>
      </div>

      {/* Reports List */}
      {filteredReports.length === 0 ? (
        <div className="bg-white dark:bg-slate-800 rounded-3xl border border-slate-200 dark:border-slate-700 p-12 text-center">
          <FileText size={64} className="text-slate-300 dark:text-slate-600 mx-auto mb-4" />
          <h3 className="text-xl font-black text-slate-900 dark:text-white mb-2">
            {labReports.length === 0 ? 'No Reports Yet' : 'No Reports Found'}
          </h3>
          <p className="text-slate-500 dark:text-slate-400 font-medium">
            {labReports.length === 0 
              ? 'Complete and validate experiments to generate lab reports'
              : 'Try a different search query'
            }
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {filteredReports.map((report, index) => (
            <motion.div
              key={report.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
              className="bg-white dark:bg-slate-800 rounded-2xl border border-slate-200 dark:border-slate-700 p-6 hover:shadow-lg hover:border-slate-300 dark:hover:border-slate-600 transition-all group"
            >
              <div className="flex items-start justify-between mb-4">
                <div className="flex-1">
                  <div className="flex items-center gap-3 mb-2">
                    <span className="px-3 py-1 bg-blue-100 text-blue-700 rounded-lg text-xs font-black">
                      {report.experimentId}
                    </span>
                    <h3 className="text-lg font-black text-slate-900 dark:text-white">
                      {report.experimentTitle}
                    </h3>
                  </div>
                  <div className="flex items-center gap-4 text-sm text-slate-500 dark:text-slate-400">
                    <div className="flex items-center gap-1">
                      <Calendar size={14} />
                      <span className="font-medium">
                        {new Date(report.generatedAt).toLocaleDateString('en-US', {
                          month: 'short',
                          day: 'numeric',
                          year: 'numeric'
                        })}
                      </span>
                    </div>
                    <div className="flex items-center gap-1">
                      <Clock size={14} />
                      <span className="font-medium">
                        {new Date(report.generatedAt).toLocaleTimeString('en-US', {
                          hour: '2-digit',
                          minute: '2-digit'
                        })}
                      </span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-4">
                  <div className="text-right">
                    <div className="flex items-center gap-2 justify-end mb-1">
                      <Award size={18} className="text-yellow-500" />
                      <span className={`text-2xl font-black ${
                        report.score >= 90 ? 'text-emerald-600' :
                        report.score >= 75 ? 'text-blue-600' :
                        report.score >= 60 ? 'text-yellow-600' : 'text-red-600'
                      }`}>
                        {report.score}%
                      </span>
                    </div>
                    <p className="text-xs text-slate-500 font-medium">Score</p>
                  </div>

                  <button
                    onClick={() => handleDownload(report)}
                    className="px-4 py-2.5 bg-slate-900 dark:bg-slate-700 text-white rounded-xl font-bold hover:bg-slate-800 dark:hover:bg-slate-600 transition-all flex items-center gap-2 shadow-sm opacity-0 group-hover:opacity-100"
                  >
                    <Download size={16} />
                    Download
                  </button>
                </div>
              </div>

              {/* Analysis Results */}
              <div className="grid grid-cols-3 gap-4 mt-4 pt-4 border-t border-slate-100 dark:border-slate-700">
                <div className="flex items-center gap-2">
                  <Zap size={16} className="text-purple-500" />
                  <div>
                    <p className="text-xs text-slate-500 font-medium">Cycle Efficiency</p>
                    <p className="font-black text-slate-900 dark:text-white">{report.analysisResults.cycleEfficiency}%</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <TrendingUp size={16} className="text-blue-500" />
                  <div>
                    <p className="text-xs text-slate-500 font-medium">Power Consumption</p>
                    <p className="font-black text-slate-900 dark:text-white">{report.analysisResults.powerConsumption}</p>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 size={16} className="text-emerald-500" />
                  <div>
                    <p className="text-xs text-slate-500 font-medium">Bus Status</p>
                    <p className="font-black text-slate-900 dark:text-white">{report.analysisResults.busStatus}</p>
                  </div>
                </div>
              </div>

              {/* Viva Preview */}
              <div className="mt-4 pt-4 border-t border-slate-100 dark:border-slate-700">
                <p className="text-sm font-bold text-slate-700 dark:text-slate-300 mb-2">
                  {report.vivaAnswers.length} Viva Questions Answered
                </p>
                <div className="space-y-1">
                  {report.vivaAnswers.slice(0, 2).map((qa, i) => (
                    <p key={i} className="text-xs text-slate-500 font-medium truncate">
                      • {qa.question}
                    </p>
                  ))}
                  {report.vivaAnswers.length > 2 && (
                    <p className="text-xs text-blue-600 font-bold">
                      +{report.vivaAnswers.length - 2} more questions
                    </p>
                  )}
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
}